# Generated by Django 4.0.6 on 2023-05-09 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_post', models.CharField(max_length=255)),
                ('empresa_post', models.CharField(max_length=255)),
                ('data_post', models.DateTimeField(default=datetime.datetime(2023, 5, 9, 9, 58, 56, 316552, tzinfo=utc))),
                ('conteudo_post', models.TextField()),
                ('excerto_post', models.TextField()),
                ('imagem_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d')),
                ('publicado_post', models.BooleanField(default=False)),
                ('categoria_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
        ),
    ]
