# Generated by Django 4.0.6 on 2023-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_categoria_post_alter_post_conteudo_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado_post',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
