# Generated by Django 4.0.6 on 2023-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_publicado_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='like_comentario',
            field=models.BooleanField(default=False, verbose_name='like'),
        ),
    ]
