# Generated by Django 4.0.6 on 2023-05-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_documento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
    ]
